// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::respawn_type::Respawn;
use super::scores_type::Scores;
use super::start_line_type::StartLine;
use super::way_point_type::WayPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum Event {
    WayPoint(WayPoint),

    Respawn(Respawn),

    StartLine(StartLine),

    Scores(Scores),

    Custom(String),
}

impl __sdk::InModule for Event {
    type Module = super::RemoteModule;
}
