// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Respawn {
    pub account_id: String,
    pub login: String,
    pub time: u32,
    pub number_respawns: u32,
    pub racetime: i32,
    pub laptime: i32,
    pub checkpoint_in_race: u32,
    pub checkpoint_in_lap: u32,
    pub speed: f32,
}

impl __sdk::InModule for Respawn {
    type Module = super::RemoteModule;
}
