// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::send_message_schedule_type::SendMessageSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendMessageSchedArgs {
    pub arg: SendMessageSchedule,
}

impl From<SendMessageSchedArgs> for super::Reducer {
    fn from(args: SendMessageSchedArgs) -> Self {
        Self::SendMessageSched { arg: args.arg }
    }
}

impl __sdk::InModule for SendMessageSchedArgs {
    type Module = super::RemoteModule;
}

pub struct SendMessageSchedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_message_sched`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_message_sched {
    /// Request that the remote module invoke the reducer `send_message_sched` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_message_sched`] callbacks.
    fn send_message_sched(&self, arg: SendMessageSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_message_sched`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendMessageSchedCallbackId`] can be passed to [`Self::remove_on_send_message_sched`]
    /// to cancel the callback.
    fn on_send_message_sched(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SendMessageSchedule) + Send + 'static,
    ) -> SendMessageSchedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_message_sched`],
    /// causing it not to run in the future.
    fn remove_on_send_message_sched(&self, callback: SendMessageSchedCallbackId);
}

impl send_message_sched for super::RemoteReducers {
    fn send_message_sched(&self, arg: SendMessageSchedule) -> __sdk::Result<()> {
        self.imp
            .call_reducer("send_message_sched", SendMessageSchedArgs { arg })
    }
    fn on_send_message_sched(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SendMessageSchedule) + Send + 'static,
    ) -> SendMessageSchedCallbackId {
        SendMessageSchedCallbackId(self.imp.on_reducer(
            "send_message_sched",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SendMessageSched { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_send_message_sched(&self, callback: SendMessageSchedCallbackId) {
        self.imp.remove_on_reducer("send_message_sched", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_message_sched`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_message_sched {
    /// Set the call-reducer flags for the reducer `send_message_sched` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_message_sched(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_message_sched for super::SetReducerFlags {
    fn send_message_sched(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_message_sched", flags);
    }
}
