// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use super::server_events_type::ServerEvents;
use super::way_point_type::WayPoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server_events`.
///
/// Obtain a handle from the [`ServerEventsTableAccess::server_events`] method on [`super::RemoteTables`],
/// like `ctx.db.server_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_events().on_insert(...)`.
pub struct ServerEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServerEvents>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerEventsTableHandle`], which mediates access to the table `server_events`.
    fn server_events(&self) -> ServerEventsTableHandle<'_>;
}

impl ServerEventsTableAccess for super::RemoteTables {
    fn server_events(&self) -> ServerEventsTableHandle<'_> {
        ServerEventsTableHandle {
            imp: self.imp.get_table::<ServerEvents>("server_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerEventsInsertCallbackId(__sdk::CallbackId);
pub struct ServerEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ServerEventsTableHandle<'ctx> {
    type Row = ServerEvents;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerEvents> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerEventsInsertCallbackId {
        ServerEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerEventsDeleteCallbackId {
        ServerEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServerEvents>("server_events");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ServerEvents>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServerEvents>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
