// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::server_events_type::ServerEvents;
use super::server_status_type::ServerStatus;
use super::user_type::User;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Server {
    pub server_id: String,
    pub owner: User,
    pub events: ServerEvents,
    pub status: ServerStatus,
}

impl __sdk::InModule for Server {
    type Module = super::RemoteModule;
}
