// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { EventPhase } from "./event_phase_type";
// Mark import as potentially unused
declare type __keep_EventPhase = EventPhase;


export type TournamentEvent = {
  id: bigint,
  tournament: bigint,
  name: string,
  phase: EventPhase,
  startingAt: __Timestamp,
  estimate: __TimeDuration | undefined,
  stages: bigint[],
};
/**
 * An object for generated helper functions.
 */
export const TournamentEvent = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U128},
        { name: "tournament", algebraicType: __AlgebraicTypeValue.U128},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "phase", algebraicType: EventPhase.getTypeScriptAlgebraicType()},
        { name: "startingAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "estimate", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimeDurationType())},
        { name: "stages", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U128)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: TournamentEvent): void {
    __AlgebraicTypeValue.serializeValue(writer, TournamentEvent.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TournamentEvent {
    return __AlgebraicTypeValue.deserializeValue(reader, TournamentEvent.getTypeScriptAlgebraicType());
  },

}

export default TournamentEvent;


