// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ServerConfigV2,
} from "./types";


export default __t.row({
  serverId: __t.u32().primaryKey().name("server_id"),
  open: __t.bool(),
  occupied: __t.bool(),
  seamless: __t.bool(),
  get config() {
    return ServerConfigV2;
  },
});
