// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::event_template_type::EventTemplate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `event_template`.
///
/// Obtain a handle from the [`EventTemplateTableAccess::event_template`] method on [`super::RemoteTables`],
/// like `ctx.db.event_template()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_template().on_insert(...)`.
pub struct EventTemplateTableHandle<'ctx> {
    imp: __sdk::TableHandle<EventTemplate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `event_template`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EventTemplateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EventTemplateTableHandle`], which mediates access to the table `event_template`.
    fn event_template(&self) -> EventTemplateTableHandle<'_>;
}

impl EventTemplateTableAccess for super::RemoteTables {
    fn event_template(&self) -> EventTemplateTableHandle<'_> {
        EventTemplateTableHandle {
            imp: self.imp.get_table::<EventTemplate>("event_template"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EventTemplateInsertCallbackId(__sdk::CallbackId);
pub struct EventTemplateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EventTemplateTableHandle<'ctx> {
    type Row = EventTemplate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EventTemplate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EventTemplateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventTemplateInsertCallbackId {
        EventTemplateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EventTemplateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EventTemplateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventTemplateDeleteCallbackId {
        EventTemplateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EventTemplateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EventTemplate>("event_template");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EventTemplate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EventTemplate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
