// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::send_message_schedule_type::SendMessageSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `send_message_schedule`.
///
/// Obtain a handle from the [`SendMessageScheduleTableAccess::send_message_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.send_message_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.send_message_schedule().on_insert(...)`.
pub struct SendMessageScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<SendMessageSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `send_message_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SendMessageScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SendMessageScheduleTableHandle`], which mediates access to the table `send_message_schedule`.
    fn send_message_schedule(&self) -> SendMessageScheduleTableHandle<'_>;
}

impl SendMessageScheduleTableAccess for super::RemoteTables {
    fn send_message_schedule(&self) -> SendMessageScheduleTableHandle<'_> {
        SendMessageScheduleTableHandle {
            imp: self
                .imp
                .get_table::<SendMessageSchedule>("send_message_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SendMessageScheduleInsertCallbackId(__sdk::CallbackId);
pub struct SendMessageScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SendMessageScheduleTableHandle<'ctx> {
    type Row = SendMessageSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SendMessageSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SendMessageScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SendMessageScheduleInsertCallbackId {
        SendMessageScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SendMessageScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SendMessageScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SendMessageScheduleDeleteCallbackId {
        SendMessageScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SendMessageScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SendMessageSchedule>("send_message_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SendMessageScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SendMessageScheduleTableHandle<'ctx> {
    type UpdateCallbackId = SendMessageScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SendMessageScheduleUpdateCallbackId {
        SendMessageScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SendMessageScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SendMessageSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SendMessageSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `send_message_schedule`,
/// which allows point queries on the field of the same name
/// via the [`SendMessageScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.send_message_schedule().scheduled_id().find(...)`.
pub struct SendMessageScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SendMessageSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SendMessageScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `send_message_schedule`.
    pub fn scheduled_id(&self) -> SendMessageScheduleScheduledIdUnique<'ctx> {
        SendMessageScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SendMessageScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SendMessageSchedule> {
        self.imp.find(col_val)
    }
}
