// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::event_type::Event;
use super::server_event_type::ServerEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server_event`.
///
/// Obtain a handle from the [`ServerEventTableAccess::server_event`] method on [`super::RemoteTables`],
/// like `ctx.db.server_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_event().on_insert(...)`.
pub struct ServerEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServerEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerEventTableHandle`], which mediates access to the table `server_event`.
    fn server_event(&self) -> ServerEventTableHandle<'_>;
}

impl ServerEventTableAccess for super::RemoteTables {
    fn server_event(&self) -> ServerEventTableHandle<'_> {
        ServerEventTableHandle {
            imp: self.imp.get_table::<ServerEvent>("server_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerEventInsertCallbackId(__sdk::CallbackId);
pub struct ServerEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ServerEventTableHandle<'ctx> {
    type Row = ServerEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerEventInsertCallbackId {
        ServerEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerEventDeleteCallbackId {
        ServerEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServerEvent>("server_event");
    _table.add_unique_constraint::<u128>("id", |row| &row.id);
}
pub struct ServerEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ServerEventTableHandle<'ctx> {
    type UpdateCallbackId = ServerEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ServerEventUpdateCallbackId {
        ServerEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ServerEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ServerEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServerEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `server_event`,
/// which allows point queries on the field of the same name
/// via the [`ServerEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_event().id().find(...)`.
pub struct ServerEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ServerEvent, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ServerEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `server_event`.
    pub fn id(&self) -> ServerEventIdUnique<'ctx> {
        ServerEventIdUnique {
            imp: self.imp.get_unique_constraint::<u128>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ServerEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<ServerEvent> {
        self.imp.find(col_val)
    }
}
