// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::server_command_type::ServerCommand;
use super::server_type::Server;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server`.
///
/// Obtain a handle from the [`ServerTableAccess::server`] method on [`super::RemoteTables`],
/// like `ctx.db.server()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server().on_insert(...)`.
pub struct ServerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Server>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerTableHandle`], which mediates access to the table `server`.
    fn server(&self) -> ServerTableHandle<'_>;
}

impl ServerTableAccess for super::RemoteTables {
    fn server(&self) -> ServerTableHandle<'_> {
        ServerTableHandle {
            imp: self.imp.get_table::<Server>("server"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerInsertCallbackId(__sdk::CallbackId);
pub struct ServerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ServerTableHandle<'ctx> {
    type Row = Server;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Server> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerInsertCallbackId {
        ServerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerDeleteCallbackId {
        ServerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Server>("server");
    _table.add_unique_constraint::<String>("server_id", |row| &row.server_id);
}
pub struct ServerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ServerTableHandle<'ctx> {
    type UpdateCallbackId = ServerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ServerUpdateCallbackId {
        ServerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ServerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Server>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Server>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `server_id` unique index on the table `server`,
/// which allows point queries on the field of the same name
/// via the [`ServerServerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server().server_id().find(...)`.
pub struct ServerServerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Server, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ServerTableHandle<'ctx> {
    /// Get a handle on the `server_id` unique index on the table `server`.
    pub fn server_id(&self) -> ServerServerIdUnique<'ctx> {
        ServerServerIdUnique {
            imp: self.imp.get_unique_constraint::<String>("server_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ServerServerIdUnique<'ctx> {
    /// Find the subscribed row whose `server_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Server> {
        self.imp.find(col_val)
    }
}
