// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tournament_stage_type::TournamentStage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tournament_stage`.
///
/// Obtain a handle from the [`TournamentStageTableAccess::tournament_stage`] method on [`super::RemoteTables`],
/// like `ctx.db.tournament_stage()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tournament_stage().on_insert(...)`.
pub struct TournamentStageTableHandle<'ctx> {
    imp: __sdk::TableHandle<TournamentStage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tournament_stage`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TournamentStageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TournamentStageTableHandle`], which mediates access to the table `tournament_stage`.
    fn tournament_stage(&self) -> TournamentStageTableHandle<'_>;
}

impl TournamentStageTableAccess for super::RemoteTables {
    fn tournament_stage(&self) -> TournamentStageTableHandle<'_> {
        TournamentStageTableHandle {
            imp: self.imp.get_table::<TournamentStage>("tournament_stage"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TournamentStageInsertCallbackId(__sdk::CallbackId);
pub struct TournamentStageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TournamentStageTableHandle<'ctx> {
    type Row = TournamentStage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TournamentStage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TournamentStageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TournamentStageInsertCallbackId {
        TournamentStageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TournamentStageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TournamentStageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TournamentStageDeleteCallbackId {
        TournamentStageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TournamentStageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TournamentStage>("tournament_stage");
    _table.add_unique_constraint::<u128>("stage_id", |row| &row.stage_id);
}
pub struct TournamentStageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TournamentStageTableHandle<'ctx> {
    type UpdateCallbackId = TournamentStageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TournamentStageUpdateCallbackId {
        TournamentStageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TournamentStageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TournamentStage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TournamentStage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `stage_id` unique index on the table `tournament_stage`,
/// which allows point queries on the field of the same name
/// via the [`TournamentStageStageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tournament_stage().stage_id().find(...)`.
pub struct TournamentStageStageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TournamentStage, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TournamentStageTableHandle<'ctx> {
    /// Get a handle on the `stage_id` unique index on the table `tournament_stage`.
    pub fn stage_id(&self) -> TournamentStageStageIdUnique<'ctx> {
        TournamentStageStageIdUnique {
            imp: self.imp.get_unique_constraint::<u128>("stage_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TournamentStageStageIdUnique<'ctx> {
    /// Find the subscribed row whose `stage_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<TournamentStage> {
        self.imp.find(col_val)
    }
}
