// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::event_status_type::EventStatus;
use super::leaderboard_type::Leaderboard;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TournamentEvent {
    pub event_id: u128,
    pub template: u128,
    pub tournament: u128,
    pub status: EventStatus,
    pub starting: String,
    pub stages: Vec<u128>,
    pub leaderboard: Leaderboard,
}

impl __sdk::InModule for TournamentEvent {
    type Module = super::RemoteModule;
}
